version: '3'
services:
  #############
  ## SERVER ##
  server:
    build:
      context: ./TV-Show-Back
      dockerfile: Dockerfile
    networks:
      - webapp
      - database
    depends_on:
      - postgres_db
    environment:
      - SECRET='¯\_(ツ)_/¯'
    restart: always
    command: ['./wait-for-it.sh', 'postgres_db:5432', '--', 'node', 'main.js']
    container_name: TV-Show-Back
  #############
  ## CLIENT ##
  client:
    build:
      context: ./TV-Show-react
      dockerfile: Dockerfile
    networks:
      - webapp
    ports:
      - 80:80
    restart: always
    container_name: TV-Show-react
  ##############
  ## POSTGRES ##
  postgres_db:
    image: postgres
    networks:
      - database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=demo
    volumes:
      - ./TV-Show-Back/database/data/prod:/var/lib/postgresql/data/
    restart: always
    container_name: postgres_db

networks:
  webapp:
    driver: bridge
  database:
    driver: bridge